files:
- generatedChecksum: F58DB2348A0FCE945652B285010E5F8A
  logicalPath: FreeRTOS/Source
  name: FreeRTOS_tasks.c
  physicalPath: ../../third_party/rtos/FreeRTOS/Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: F58DB2348A0FCE945652B285010E5F8A
- generatedChecksum: null
  logicalPath: ''
  name: app_task1.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: null
  logicalPath: ''
  name: app_task2.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: null
  logicalPath: ''
  name: app_task3.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 3E59F5E2CC619BC6273282ECE032DF6F
  logicalPath: config/pic32mm_curiosity/bsp
  name: bsp.c
  physicalPath: bsp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3E59F5E2CC619BC6273282ECE032DF6F
- generatedChecksum: 8ACE0DEBD82F6829438A4674565451FB
  logicalPath: FreeRTOS/Source
  name: croutine.c
  physicalPath: ../../third_party/rtos/FreeRTOS/Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8ACE0DEBD82F6829438A4674565451FB
- generatedChecksum: B3B5445B14BD9B6A35F1C5B995C9BBF7
  logicalPath: FreeRTOS/Source
  name: event_groups.c
  physicalPath: ../../third_party/rtos/FreeRTOS/Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: B3B5445B14BD9B6A35F1C5B995C9BBF7
- generatedChecksum: 4BBDE3B7B0DAEE2CA5A8F519001D5BFF
  logicalPath: config/pic32mm_curiosity
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4BBDE3B7B0DAEE2CA5A8F519001D5BFF
- generatedChecksum: B7DBFD6F500AAD4713403E985EB18EAE
  logicalPath: config/pic32mm_curiosity
  name: freertos_hooks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: B7DBFD6F500AAD4713403E985EB18EAE
- generatedChecksum: 972E955D94A63BA89BF6ABD6AADB1023
  logicalPath: FreeRTOS/Source/portable/MemMang
  name: heap_1.c
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/portable/MemMang
  security: NON_SECURE
  type: SOURCE
  userChecksum: 972E955D94A63BA89BF6ABD6AADB1023
- generatedChecksum: 895578E318951AED3D10B79912DB933A
  logicalPath: config/pic32mm_curiosity
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 895578E318951AED3D10B79912DB933A
- generatedChecksum: 40EE429B9A5E0D7D4145B6C9C52E84DA
  logicalPath: config/pic32mm_curiosity
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 40EE429B9A5E0D7D4145B6C9C52E84DA
- generatedChecksum: 5D0063DFDA25A7E9DB70EF2EF49CDF4D
  logicalPath: config/pic32mm_curiosity
  name: interrupts_a.S
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5D0063DFDA25A7E9DB70EF2EF49CDF4D
- generatedChecksum: 3FEE521CEF14928AE38E7FA9BF6D75E6
  logicalPath: FreeRTOS/Source
  name: list.c
  physicalPath: ../../third_party/rtos/FreeRTOS/Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3FEE521CEF14928AE38E7FA9BF6D75E6
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: D864665CBB58E30F9FB47FE6EF29141D
  logicalPath: config/pic32mm_curiosity/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: D864665CBB58E30F9FB47FE6EF29141D
- generatedChecksum: E5A7EF8E375994F637F1A71E6F32E529
  logicalPath: config/pic32mm_curiosity/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: E5A7EF8E375994F637F1A71E6F32E529
- generatedChecksum: 367056863A6B2B7A47EB8DC0B5892822
  logicalPath: config/pic32mm_curiosity/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 367056863A6B2B7A47EB8DC0B5892822
- generatedChecksum: 25E51DD4469A699703C800AD6F5515A3
  logicalPath: config/pic32mm_curiosity/peripheral/uart
  name: plib_uart2.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 25E51DD4469A699703C800AD6F5515A3
- generatedChecksum: B4D0080055B389946BA92394CA6F27AD
  logicalPath: FreeRTOS/Source/portable/MPLAB/PIC32MM_GPL
  name: port.c
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MM_GPL
  security: NON_SECURE
  type: SOURCE
  userChecksum: B4D0080055B389946BA92394CA6F27AD
- generatedChecksum: 0333D5D341B0BA83EB19C16C74FCAC9F
  logicalPath: FreeRTOS/Source/portable/MPLAB/PIC32MM_GPL
  name: port_asm.S
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MM_GPL
  security: NON_SECURE
  type: SOURCE
  userChecksum: 0333D5D341B0BA83EB19C16C74FCAC9F
- generatedChecksum: 09041728D74A4E3A32C7D4EAA96C4EE7
  logicalPath: FreeRTOS/Source
  name: queue.c
  physicalPath: ../../third_party/rtos/FreeRTOS/Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: 09041728D74A4E3A32C7D4EAA96C4EE7
- generatedChecksum: D6CF30BDCE1A813D9ACF3905EBD6A871
  logicalPath: FreeRTOS/Source
  name: stream_buffer.c
  physicalPath: ../../third_party/rtos/FreeRTOS/Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: D6CF30BDCE1A813D9ACF3905EBD6A871
- generatedChecksum: 05C70EEC247FE8CD7316D18F106FDCAB
  logicalPath: config/pic32mm_curiosity
  name: tasks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 05C70EEC247FE8CD7316D18F106FDCAB
- generatedChecksum: F1B86F6E1527FD59A8713B67564F2898
  logicalPath: FreeRTOS/Source
  name: timers.c
  physicalPath: ../../third_party/rtos/FreeRTOS/Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: F1B86F6E1527FD59A8713B67564F2898
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config/pic32mm_curiosity/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: AF3A8D8AA610E7DFD3E38DDAC5E42074
  logicalPath: FreeRTOS/Source/include
  name: FreeRTOS.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: AF3A8D8AA610E7DFD3E38DDAC5E42074
- generatedChecksum: D48E5A691807629BF624F0F342E740EC
  logicalPath: config/pic32mm_curiosity
  name: FreeRTOSConfig.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: D48E5A691807629BF624F0F342E740EC
- generatedChecksum: 5618FA73F2F198C58F0EC1C66481BAEC
  logicalPath: FreeRTOS/Source/portable/MPLAB/PIC32MM_GPL
  name: ISR_Support.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MM_GPL
  security: NON_SECURE
  type: HEADER
  userChecksum: 5618FA73F2F198C58F0EC1C66481BAEC
- generatedChecksum: null
  logicalPath: ''
  name: app_task1.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: null
  logicalPath: ''
  name: app_task2.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: null
  logicalPath: ''
  name: app_task3.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: 05B8EFFF8D8324D384589C384F6A1ADA
  logicalPath: config/pic32mm_curiosity/bsp
  name: bsp.h
  physicalPath: bsp
  security: NON_SECURE
  type: HEADER
  userChecksum: 05B8EFFF8D8324D384589C384F6A1ADA
- generatedChecksum: 7A852268CAA1F0FBB9E75D327532882A
  logicalPath: config/pic32mm_curiosity
  name: configuration.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 7A852268CAA1F0FBB9E75D327532882A
- generatedChecksum: 48B661D8C967C6BC397001F10FB43D1D
  logicalPath: FreeRTOS/Source/include
  name: croutine.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 48B661D8C967C6BC397001F10FB43D1D
- generatedChecksum: 38573D4FA9B49E321159483DFD58B7E1
  logicalPath: config/pic32mm_curiosity
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 38573D4FA9B49E321159483DFD58B7E1
- generatedChecksum: 1EA4EDD5EA90F43EC407DE32441159A9
  logicalPath: FreeRTOS/Source/include
  name: deprecated_definitions.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 1EA4EDD5EA90F43EC407DE32441159A9
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mm_curiosity
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: B1D1D455E111FA70C46AD40562D78CE2
  logicalPath: FreeRTOS/Source/include
  name: event_groups.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: B1D1D455E111FA70C46AD40562D78CE2
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mm_curiosity
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: FE17D325A06479D956285C5438994B83
  logicalPath: FreeRTOS/Source/include
  name: list.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: FE17D325A06479D956285C5438994B83
- generatedChecksum: DDE2C9D46642D120A0202AC851E1A777
  logicalPath: FreeRTOS/Source/include
  name: message_buffer.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: DDE2C9D46642D120A0202AC851E1A777
- generatedChecksum: 2D674B8B1FCF07504AF90FA5CE2F9A23
  logicalPath: FreeRTOS/Source/include
  name: mpu_prototypes.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 2D674B8B1FCF07504AF90FA5CE2F9A23
- generatedChecksum: 953D372D8F7991D4F86AD4ABD42AE4CE
  logicalPath: FreeRTOS/Source/include
  name: mpu_wrappers.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 953D372D8F7991D4F86AD4ABD42AE4CE
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mm_curiosity/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: F71A20BA61477D7082FBF03703A4CD38
  logicalPath: config/pic32mm_curiosity/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: F71A20BA61477D7082FBF03703A4CD38
- generatedChecksum: 36CFDF4AD5D53F43CFC636AB6F689530
  logicalPath: config/pic32mm_curiosity/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 36CFDF4AD5D53F43CFC636AB6F689530
- generatedChecksum: 93CC14A3CC9AF9F15876EE3C336DD97E
  logicalPath: config/pic32mm_curiosity/peripheral/uart
  name: plib_uart2.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 93CC14A3CC9AF9F15876EE3C336DD97E
- generatedChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
  logicalPath: config/pic32mm_curiosity/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
- generatedChecksum: 5A686FF678CBFBB4A1FEB86B66DCEC98
  logicalPath: FreeRTOS/Source/include
  name: portable.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 5A686FF678CBFBB4A1FEB86B66DCEC98
- generatedChecksum: 550F08BF34A2F704778BDA3EB71BAC8F
  logicalPath: FreeRTOS/Source/portable/MPLAB/PIC32MM_GPL
  name: portmacro.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MM_GPL
  security: NON_SECURE
  type: HEADER
  userChecksum: 550F08BF34A2F704778BDA3EB71BAC8F
- generatedChecksum: 696F66B2428CC530389C53B5FE617CE1
  logicalPath: FreeRTOS/Source/include
  name: projdefs.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 696F66B2428CC530389C53B5FE617CE1
- generatedChecksum: 6CB1FF8C27E6755C63D75369D1D7A37A
  logicalPath: FreeRTOS/Source/include
  name: queue.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 6CB1FF8C27E6755C63D75369D1D7A37A
- generatedChecksum: 9F1AE7D29D09ED8CC21F3DA08049FB79
  logicalPath: FreeRTOS/Source/include
  name: semphr.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 9F1AE7D29D09ED8CC21F3DA08049FB79
- generatedChecksum: D0D11C3D2D1BD585018AE271E1AC3B8F
  logicalPath: FreeRTOS/Source/include
  name: stack_macros.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: D0D11C3D2D1BD585018AE271E1AC3B8F
- generatedChecksum: 7C71A9D2BEF16AC21C17ED5C2452C263
  logicalPath: FreeRTOS/Source/include
  name: stream_buffer.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 7C71A9D2BEF16AC21C17ED5C2452C263
- generatedChecksum: 84B3224817BDD8B37961BB3B3441E134
  logicalPath: FreeRTOS/Source/include
  name: task.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 84B3224817BDD8B37961BB3B3441E134
- generatedChecksum: C8BB70E2423A57902E9FDC0C9EC81F8D
  logicalPath: FreeRTOS/Source/include
  name: timers.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: C8BB70E2423A57902E9FDC0C9EC81F8D
- generatedChecksum: 2C8543317B3F067432097AB9BD3E8672
  logicalPath: config/pic32mm_curiosity
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2C8543317B3F067432097AB9BD3E8672
- generatedChecksum: null
  logicalPath: config/pic32mm_curiosity
  name: user.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: EBD6E51AC74F4B4A4AC25BE63E43F94C
  logicalPath: config/pic32mm_curiosity
  name: p32MM0064GPL036.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: EBD6E51AC74F4B4A4AC25BE63E43F94C
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src/third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MM_GPL;../src/third_party/rtos/FreeRTOS/Source/include;
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mm_curiosity;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: true
  category: C32-AS
  delimiter: ;
  key: extra-include-directories-for-assembler
  security: NON_SECURE
  value: ../src/third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MM_GPL;../src/third_party/rtos/FreeRTOS/Source/include;../src/config/pic32mm_curiosity;
- append: true
  category: C32-AS
  delimiter: ;
  key: extra-include-directories-for-preprocessor
  security: NON_SECURE
  value: ../src/third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MM_GPL;../src/third_party/rtos/FreeRTOS/Source/include;../src/config/pic32mm_curiosity;
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src/third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MM_GPL;../src/third_party/rtos/FreeRTOS/Source/include;
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mm_curiosity;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
