files:
- generatedChecksum: null
  logicalPath: ''
  name: app.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 5B0ABC7040175601AE3BFF86683325BD
  logicalPath: config/pic32mm_usb_curiosity/bsp
  name: bsp.c
  physicalPath: bsp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5B0ABC7040175601AE3BFF86683325BD
- generatedChecksum: 4BBDE3B7B0DAEE2CA5A8F519001D5BFF
  logicalPath: config/pic32mm_usb_curiosity
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4BBDE3B7B0DAEE2CA5A8F519001D5BFF
- generatedChecksum: C2EC3C5258E2D16A0AE4D071992B6E57
  logicalPath: config/pic32mm_usb_curiosity
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: C2EC3C5258E2D16A0AE4D071992B6E57
- generatedChecksum: 476A717322A95E9C71A1E546E023E2E8
  logicalPath: config/pic32mm_usb_curiosity
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 476A717322A95E9C71A1E546E023E2E8
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: FE07C36C086699B2855BCDFB8F2F40EC
  logicalPath: config/pic32mm_usb_curiosity/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: FE07C36C086699B2855BCDFB8F2F40EC
- generatedChecksum: 79CEA15125225D752B3FE8AC135EF740
  logicalPath: config/pic32mm_usb_curiosity/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 79CEA15125225D752B3FE8AC135EF740
- generatedChecksum: FC4C4C5090ABE2240549E155607F57BA
  logicalPath: config/pic32mm_usb_curiosity/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: FC4C4C5090ABE2240549E155607F57BA
- generatedChecksum: 255237C152E0A045A585C577DC6E93EE
  logicalPath: config/pic32mm_usb_curiosity/peripheral/uart
  name: plib_uart3.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 255237C152E0A045A585C577DC6E93EE
- generatedChecksum: 20C22A19D5DC74DEBFC4CCCA83B6F603
  logicalPath: config/pic32mm_usb_curiosity/system/console
  name: sys_console.c
  physicalPath: system/console/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 20C22A19D5DC74DEBFC4CCCA83B6F603
- generatedChecksum: 5BA0902794A8669B3FE37E8A8BEE9D65
  logicalPath: config/pic32mm_usb_curiosity/system/console
  name: sys_console_local.h
  physicalPath: system/console/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5BA0902794A8669B3FE37E8A8BEE9D65
- generatedChecksum: CA5E9B63704372DE5FBC0BDC006B16C3
  logicalPath: config/pic32mm_usb_curiosity/system/console
  name: sys_console_uart.c
  physicalPath: system/console/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: CA5E9B63704372DE5FBC0BDC006B16C3
- generatedChecksum: 767495C6A39617A915D8107093DC1A72
  logicalPath: config/pic32mm_usb_curiosity/system/console
  name: sys_console_uart.h
  physicalPath: system/console/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 767495C6A39617A915D8107093DC1A72
- generatedChecksum: 5D10B9438117B64220180660AB022150
  logicalPath: config/pic32mm_usb_curiosity/system/console
  name: sys_console_uart_definitions.h
  physicalPath: system/console/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5D10B9438117B64220180660AB022150
- generatedChecksum: 68C0D499B9EDAA3BFD7E131A48514212
  logicalPath: config/pic32mm_usb_curiosity/system/debug
  name: sys_debug.c
  physicalPath: system/debug/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 68C0D499B9EDAA3BFD7E131A48514212
- generatedChecksum: B8C6C7356AC7841AECC7C779040F745C
  logicalPath: config/pic32mm_usb_curiosity/system/debug
  name: sys_debug_local.h
  physicalPath: system/debug/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: B8C6C7356AC7841AECC7C779040F745C
- generatedChecksum: C95CE0ABB86E6B11CF77E8891D294510
  logicalPath: config/pic32mm_usb_curiosity/system/int
  name: sys_int.c
  physicalPath: system/int/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: C95CE0ABB86E6B11CF77E8891D294510
- generatedChecksum: DE51BB8F6FDBC39FB049CB2A14E56B25
  logicalPath: config/pic32mm_usb_curiosity
  name: tasks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: DE51BB8F6FDBC39FB049CB2A14E56B25
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config/pic32mm_usb_curiosity/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: null
  logicalPath: ''
  name: app.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: 2271D58042EA06162EEA3285E2676670
  logicalPath: config/pic32mm_usb_curiosity/bsp
  name: bsp.h
  physicalPath: bsp
  security: NON_SECURE
  type: HEADER
  userChecksum: 2271D58042EA06162EEA3285E2676670
- generatedChecksum: 9E6FBD88FCCB553D64D4536902580AB5
  logicalPath: config/pic32mm_usb_curiosity
  name: configuration.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 9E6FBD88FCCB553D64D4536902580AB5
- generatedChecksum: F6F2F55891C4E19C9E594338C8C9D2A7
  logicalPath: config/pic32mm_usb_curiosity
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: F6F2F55891C4E19C9E594338C8C9D2A7
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mm_usb_curiosity
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 1D2094DFA60F847FFD4E8153B6E78027
  logicalPath: config/pic32mm_usb_curiosity/driver
  name: driver.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: 1D2094DFA60F847FFD4E8153B6E78027
- generatedChecksum: CC7DFCC51CD25171A3E400E18969354F
  logicalPath: config/pic32mm_usb_curiosity/driver
  name: driver_common.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: CC7DFCC51CD25171A3E400E18969354F
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mm_usb_curiosity
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: F0AD88762263B7CB89B02AB4F5876059
  logicalPath: config/pic32mm_usb_curiosity/osal
  name: osal.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: F0AD88762263B7CB89B02AB4F5876059
- generatedChecksum: 0AC88C49E4585B606FD5AC6804F0C340
  logicalPath: config/pic32mm_usb_curiosity/osal
  name: osal_definitions.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: 0AC88C49E4585B606FD5AC6804F0C340
- generatedChecksum: B040122CCA94A0636810D6F15F13B751
  logicalPath: config/pic32mm_usb_curiosity/osal
  name: osal_impl_basic.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: B040122CCA94A0636810D6F15F13B751
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mm_usb_curiosity/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 471535DBA871A956FB7FAC6C66FCD8C1
  logicalPath: config/pic32mm_usb_curiosity/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 471535DBA871A956FB7FAC6C66FCD8C1
- generatedChecksum: D0226D294D437AF5854104B8AD97C8CE
  logicalPath: config/pic32mm_usb_curiosity/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: D0226D294D437AF5854104B8AD97C8CE
- generatedChecksum: 25A38C9BEB4255417BD84E5B5C82CBCB
  logicalPath: config/pic32mm_usb_curiosity/peripheral/uart
  name: plib_uart3.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 25A38C9BEB4255417BD84E5B5C82CBCB
- generatedChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
  logicalPath: config/pic32mm_usb_curiosity/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
- generatedChecksum: 91CB36F6EC29DAA7C584282A875E5CBA
  logicalPath: config/pic32mm_usb_curiosity/system/console
  name: sys_console.h
  physicalPath: system/console
  security: NON_SECURE
  type: HEADER
  userChecksum: 91CB36F6EC29DAA7C584282A875E5CBA
- generatedChecksum: 6972608768DDBE6E37A2D81B83DF490B
  logicalPath: config/pic32mm_usb_curiosity/system/debug
  name: sys_debug.h
  physicalPath: system/debug
  security: NON_SECURE
  type: HEADER
  userChecksum: 6972608768DDBE6E37A2D81B83DF490B
- generatedChecksum: 47330C2D8F204B2B69F8A86240A564B6
  logicalPath: config/pic32mm_usb_curiosity/system/int
  name: sys_int.h
  physicalPath: system/int
  security: NON_SECURE
  type: HEADER
  userChecksum: 47330C2D8F204B2B69F8A86240A564B6
- generatedChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
  logicalPath: config/pic32mm_usb_curiosity/system/int
  name: sys_int_mapping.h
  physicalPath: system/int
  security: NON_SECURE
  type: HEADER
  userChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
- generatedChecksum: BE95B4F134C5C929787B9DA6FDBF3501
  logicalPath: config/pic32mm_usb_curiosity/system
  name: system.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: BE95B4F134C5C929787B9DA6FDBF3501
- generatedChecksum: C3F5136D520DAC4416512EBFCCA023C3
  logicalPath: config/pic32mm_usb_curiosity/system
  name: system_common.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: C3F5136D520DAC4416512EBFCCA023C3
- generatedChecksum: 1C75A8A6B60598A2FD0D533F57839B72
  logicalPath: config/pic32mm_usb_curiosity/system
  name: system_module.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: 1C75A8A6B60598A2FD0D533F57839B72
- generatedChecksum: 2C8543317B3F067432097AB9BD3E8672
  logicalPath: config/pic32mm_usb_curiosity
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2C8543317B3F067432097AB9BD3E8672
- generatedChecksum: null
  logicalPath: config/pic32mm_usb_curiosity
  name: user.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: C469F285BA2018DB29C8BEBCBE863C37
  logicalPath: config/pic32mm_usb_curiosity
  name: p32MM0256GPM064.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: C469F285BA2018DB29C8BEBCBE863C37
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mm_usb_curiosity;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mm_usb_curiosity;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
