configName: pic32mm_usb_curiosity
folderName: pic32mm_usb_curiosity
format_version: v1.0
frameworkPath: ..\..\..\..\..\..\..
processor: PIC32MM0256GPM064
projectName: async_i2c_eeprom_pic32mm_usb_curiosity
settings:
  PackageFilter: bootloader;bootloader_apps_i2c;bootloader_apps_usb;bsp;core;crypto;crypto_apps_encrypt_decrypt;csp;csp_apps_pic32mk;quick_docs;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MM_GPM_DFP\1.3.44\atdf\PIC32MM0256GPM064.atdf
