configName: pic32mm_usb_curiosity
folderName: pic32mm_usb_curiosity
format_version: v1.0
frameworkPath: ..\..\..\..\..\..\..
processor: PIC32MM0256GPM064
projectName: async_i2c_eeprom_pic32mm_usb_curiosity
settings:
  PackageFilter: bootloader;bsp;cec173x_soteria_lib;core;crypto;csp;Devices;dev_packs;harmony-services;net;quick_docs;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MM_GPM_DFP\1.3.50\atdf\PIC32MM0256GPM064.atdf
